name = "fortmax-ticketz-api"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "TicketzBackend"
image = "../backend/Dockerfile.cloudflare"
max_instances = 3

[[durable_objects.bindings]]
name = "TICKETZ_BACKEND"
class_name = "TicketzBackend"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TicketzBackend"]

[vars]
HOST = "0.0.0.0"
PORT = "3000"
FRONTEND_URL = "https://suporte.fortmax.com.br"
BACKEND_URL = "https://api.fortmax.com.br"
DB_DIALECT = "postgres"
DB_HOST = "db.tcwtpkadwrsbdvehsmfy.supabase.co"
DB_PORT = "5432"
DB_USER = "postgres"
DB_NAME = "postgres"
DB_SCHEMA = "ticketz"
DB_SSL = "true"
DB_SSL_REJECT_UNAUTHORIZED = "false"
DB_TIMEZONE = "-03:00"
DB_MAX_CONNECTIONS = "5"
DB_MIN_CONNECTIONS = "1"
REDIS_URI = "redis://127.0.0.1:6379"
VERIFY_TOKEN = "ticketz"
SOCKET_ADMIN = "true"
TZ = "America/Sao_Paulo"
USER_LIMIT = "10000"
CONNECTIONS_LIMIT = "100000"
CLOSED_SEND_BY_ME = "true"

[[routes]]
pattern = "api.fortmax.com.br/*"
zone_name = "fortmax.com.br"
